spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: ecommercefinal
      host: localhost
      port: 27017
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 1800000
  mail:
    host: smtp.gmail.com
    port: 587
    username: coderhouseprueba2702@gmail.com
    password: nvmleadjqfigqdhi
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
jwt:
  expiration: 1800000
  secret: springbootjwtcoderhouse

server:
  port: 8080