spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: ecommercefinal
      host: localhost
      port: 27017

server:
  port: 8080
